// DEMO / ÖRNEK VERİ — API boşken salonlara düzeni göstermek için durur.
// Gerçek isim/fiyat YOK: tüm salon/hoca/kullanıcı/ders adları "Örnek ..." placeholder,
// fiyatlar 0. Mahalle ve spor kategorileri gerçek (yapıyı anlatmak için).
export const mockUsers = [
  { id: 1, username: 'ornek_kullanici_1', fullName: 'Örnek Kullanıcı 1', bio: 'Örnek biyografi', neighborhood: 'Beşiktaş', tier: { name: 'Elit', icon: 'medal', color: '#F59E0B', pointRate: 4 }, topSports: [{ name: 'Yoga', icon: 'yoga', count: 34, color: '#ed719e' }, { name: 'HIIT', icon: 'hiit', count: 22, color: '#EA580C' }], stats: { totalLessons: 84, thisMonth: 12, streak: 6, noCancel: 18, sameVenue: 14 }, badges: [{ name: 'İstikrarlı', icon: 'target', color: '#8B5CF6' }, { name: 'Disiplinli', icon: 'strength', color: '#10B981' }], leaderboard: { istanbul: 142, neighborhood: 8 } },
  { id: 2, username: 'ornek_kullanici_2', fullName: 'Örnek Kullanıcı 2', bio: 'Örnek biyografi', neighborhood: 'Kadıköy', tier: { name: 'Profesyonel', icon: 'medal', color: '#3B82F6', pointRate: 3 }, topSports: [{ name: 'Boks', icon: 'boxing', count: 40, color: '#DC2626' }, { name: 'Crossfit', icon: 'crossfit', count: 20, color: '#B45309' }], stats: { totalLessons: 52, thisMonth: 8, streak: 4, noCancel: 12, sameVenue: 8 }, badges: [{ name: 'Disiplinli', icon: 'strength', color: '#10B981' }], leaderboard: { istanbul: 280, neighborhood: 15 } },
  { id: 3, username: 'ornek_kullanici_3', fullName: 'Örnek Kullanıcı 3', bio: 'Örnek biyografi', neighborhood: 'Şişli', tier: { name: 'Olimpik', icon: 'medal', color: '#DC2626', pointRate: 5 }, topSports: [{ name: 'Yoga', icon: 'yoga', count: 80, color: '#ed719e' }, { name: 'Pilates', icon: 'pilates', count: 45, color: '#e2b67d' }], stats: { totalLessons: 134, thisMonth: 18, streak: 22, noCancel: 40, sameVenue: 35 }, badges: [{ name: 'İstikrarlı', icon: 'target', color: '#8B5CF6' }, { name: 'Disiplinli', icon: 'strength', color: '#10B981' }, { name: 'Sadık', icon: 'heart', color: '#EF4444' }], leaderboard: { istanbul: 24, neighborhood: 2 } },
  { id: 4, username: 'ornek_kullanici_4', fullName: 'Örnek Kullanıcı 4', bio: 'Örnek biyografi', neighborhood: 'Ataşehir', tier: { name: 'Elit', icon: 'medal', color: '#F59E0B', pointRate: 4 }, topSports: [{ name: 'Tenis', icon: 'padel', count: 50, color: '#65A30D' }], stats: { totalLessons: 78, thisMonth: 10, streak: 8, noCancel: 20, sameVenue: 18 }, badges: [{ name: 'Sadık', icon: 'heart', color: '#EF4444' }], leaderboard: { istanbul: 168, neighborhood: 12 } },
  { id: 5, username: 'ornek_kullanici_5', fullName: 'Örnek Kullanıcı 5', bio: 'Örnek biyografi', neighborhood: 'Beşiktaş', tier: { name: 'Sporcu', icon: 'medal', color: '#10B981', pointRate: 2 }, topSports: [{ name: 'Pilates', icon: 'pilates', count: 12, color: '#e2b67d' }, { name: 'Dans', icon: 'dance', count: 8, color: '#9333EA' }], stats: { totalLessons: 20, thisMonth: 5, streak: 2, noCancel: 5, sameVenue: 4 }, badges: [], leaderboard: { istanbul: 890, neighborhood: 42 } },
  { id: 6, username: 'ornek_kullanici_6', fullName: 'Örnek Kullanıcı 6', bio: 'Örnek biyografi', neighborhood: 'Levent', tier: { name: 'Profesyonel', icon: 'medal', color: '#3B82F6', pointRate: 3 }, topSports: [{ name: 'Crossfit', icon: 'crossfit', count: 30, color: '#B45309' }, { name: 'HIIT', icon: 'hiit', count: 18, color: '#EA580C' }], stats: { totalLessons: 48, thisMonth: 7, streak: 3, noCancel: 10, sameVenue: 6 }, badges: [{ name: 'İstikrarlı', icon: 'target', color: '#8B5CF6' }], leaderboard: { istanbul: 310, neighborhood: 18 } },
]

export const mockInstructors = [
  { id: 1001, userId: null, venueId: 1001, fullName: 'Örnek Hoca 1', bio: 'Örnek eğitmen açıklaması', bioEn: 'Sample instructor description', specialty: 'Örnek Uzmanlık', specialtyEn: 'Sample Specialty', avgRating: 4.9, totalReviews: 128, icon: 'yoga', color: '#ed719e', isActive: true },
  { id: 1002, userId: null, venueId: 1001, fullName: 'Örnek Hoca 2', bio: 'Örnek eğitmen açıklaması', bioEn: 'Sample instructor description', specialty: 'Örnek Uzmanlık', specialtyEn: 'Sample Specialty', avgRating: 4.8, totalReviews: 96, icon: 'weightlifting', color: '#3B82F6', isActive: true },
  { id: 1003, userId: null, venueId: 1002, fullName: 'Örnek Hoca 3', bio: 'Örnek eğitmen açıklaması', bioEn: 'Sample instructor description', specialty: 'Örnek Uzmanlık', specialtyEn: 'Sample Specialty', avgRating: 4.8, totalReviews: 112, icon: 'pilates', color: '#e2b67d', isActive: true },
  { id: 1004, userId: null, venueId: 1003, fullName: 'Örnek Hoca 4', bio: 'Örnek eğitmen açıklaması', bioEn: 'Sample instructor description', specialty: 'Örnek Uzmanlık', specialtyEn: 'Sample Specialty', avgRating: 4.7, totalReviews: 89, icon: 'boxing', color: '#DC2626', isActive: true },
  { id: 1005, userId: null, venueId: 1005, fullName: 'Örnek Hoca 5', bio: 'Örnek eğitmen açıklaması', bioEn: 'Sample instructor description', specialty: 'Örnek Uzmanlık', specialtyEn: 'Sample Specialty', avgRating: 4.9, totalReviews: 156, icon: 'hiit', color: '#EA580C', isActive: true },
  { id: 1006, userId: null, venueId: 1001, fullName: 'Örnek Hoca 6', bio: 'Örnek eğitmen açıklaması', bioEn: 'Sample instructor description', specialty: 'Örnek Uzmanlık', specialtyEn: 'Sample Specialty', avgRating: 4.7, totalReviews: 74, icon: 'wellness', color: '#10B981', isActive: true },
]

export const mockVenues = [
  { id: 1001, name: 'Örnek Salon 1', description: 'Örnek salon açıklaması', descriptionEn: 'Sample venue description', category: 'Yoga · Pilates · Meditasyon', categoryEn: 'Yoga · Pilates · Meditation', address: 'Örnek Adres, İstanbul', neighborhood: 'Beşiktaş', avgRating: 4.9, totalReviews: 214, isVerified: true, coverEmoji: 'yoga', color: '#ed719e', amenities: ['Duş', 'Soyunma odası', 'Klima', 'Mat dahil', 'Ücretsiz su', 'Wifi', 'Otopark'], instructorIds: [1001, 1002, 1006] },
  { id: 1002, name: 'Örnek Salon 2', description: 'Örnek salon açıklaması', descriptionEn: 'Sample venue description', category: 'Pilates · Yoga', categoryEn: 'Pilates · Yoga', address: 'Örnek Adres, İstanbul', neighborhood: 'Kadıköy', avgRating: 4.8, totalReviews: 178, isVerified: true, coverEmoji: 'pilates', color: '#e2b67d', amenities: ['Reformer', 'Duş', 'Klima', 'Havlu dahil', 'Ücretsiz su'], instructorIds: [1003] },
  { id: 1003, name: 'Örnek Salon 3', description: 'Örnek salon açıklaması', descriptionEn: 'Sample venue description', category: 'Boks · Kickboks · MMA', categoryEn: 'Boxing · Kickboxing · MMA', address: 'Örnek Adres, İstanbul', neighborhood: 'Şişli', avgRating: 4.7, totalReviews: 142, isVerified: true, coverEmoji: 'boxing', color: '#DC2626', amenities: ['Ring', 'Kum torbası', 'Eldiven kiralama', 'Duş', 'Soyunma odası'], instructorIds: [1004] },
  { id: 1005, name: 'Örnek Salon 4', description: 'Örnek salon açıklaması', descriptionEn: 'Sample venue description', category: 'HIIT · CrossFit · Fonksiyonel', categoryEn: 'HIIT · CrossFit · Functional', address: 'Örnek Adres, İstanbul', neighborhood: 'Levent', avgRating: 4.9, totalReviews: 267, isVerified: true, coverEmoji: 'hiit', color: '#EA580C', amenities: ['Modern ekipman', 'Duş', 'Klima', 'Havlu dahil', 'Protein bar', 'Otopark'], instructorIds: [1005] },
]

export const mockClasses = [
  { id: 1001, title: 'Örnek Ders 1', venueId: 1001, instructorId: 1001, category: 'Yoga', icon: 'yoga', time: 'Bugün 09:00', date: '10 Haziran 2026, Salı', duration: '60 dk', basePrice: 0, spots: 4, capacity: 12, rating: 4.9, totalReviews: 214, neighborhood: 'Beşiktaş', color: '#ed719e', description: 'Örnek ders açıklaması', descriptionEn: 'Sample class description', amenities: ['Yoga matı dahil', 'Duş imkânı', 'Ücretsiz su', 'Klima'] },
  { id: 1002, title: 'Örnek Ders 2', venueId: 1002, instructorId: 1003, category: 'Pilates', icon: 'pilates', time: 'Bugün 10:30', date: '10 Haziran 2026, Salı', duration: '50 dk', basePrice: 0, spots: 2, capacity: 8, rating: 4.8, totalReviews: 178, neighborhood: 'Kadıköy', color: '#e2b67d', description: 'Örnek ders açıklaması', descriptionEn: 'Sample class description', amenities: ['Reformer dahil', 'Havlu dahil', 'Ücretsiz su'] },
  { id: 1003, title: 'Örnek Ders 3', titleEn: 'Sample Class 3', venueId: 1003, instructorId: 1004, category: 'Boks', icon: 'boxing', time: 'Bugün 12:00', date: '10 Haziran 2026, Salı', duration: '60 dk', basePrice: 0, spots: 6, capacity: 15, rating: 4.7, totalReviews: 142, neighborhood: 'Şişli', color: '#DC2626', description: 'Örnek ders açıklaması', descriptionEn: 'Sample class description', amenities: ['Eldiven kiralama', 'Kask dahil', 'Duş'] },
  { id: 1004, title: 'Örnek Ders 4', venueId: 1005, instructorId: 1005, category: 'HIIT', icon: 'hiit', time: 'Bugün 18:00', date: '10 Haziran 2026, Salı', duration: '45 dk', basePrice: 0, spots: 8, capacity: 20, rating: 4.9, totalReviews: 267, neighborhood: 'Levent', color: '#EA580C', description: 'Örnek ders açıklaması', descriptionEn: 'Sample class description', amenities: ['Ekipman dahil', 'Havlu dahil', 'Protein içeceği'] },
  { id: 1005, title: 'Örnek Ders 5', venueId: 1001, instructorId: 1001, category: 'Yoga', icon: 'yoga', time: 'Yarın 09:00', date: '11 Haziran 2026, Çarşamba', duration: '75 dk', basePrice: 0, spots: 8, capacity: 12, rating: 4.9, totalReviews: 186, neighborhood: 'Beşiktaş', color: '#ed719e', description: 'Örnek ders açıklaması', descriptionEn: 'Sample class description', amenities: ['Yoga matı dahil', 'Yoga bloğu dahil', 'Ücretsiz su'] },
  { id: 1006, title: 'Örnek Ders 6', titleEn: 'Sample Class 6', venueId: 1001, instructorId: 1002, category: 'Yoga', icon: 'strength', time: 'Yarın 12:00', date: '11 Haziran 2026, Çarşamba', duration: '60 dk', basePrice: 0, spots: 5, capacity: 12, rating: 4.8, totalReviews: 156, neighborhood: 'Beşiktaş', color: '#3B82F6', description: 'Örnek ders açıklaması', descriptionEn: 'Sample class description', amenities: ['Yoga matı dahil', 'Duş', 'Ücretsiz su'] },
]

// Drop-in sporları (Halı Saha/Basketbol/Padel) şimdilik kaldırıldı — yeri gelince eklenecek.
export const mockDropInSlots: any[] = []

// Sosyal sayfası demo verisi (API boşsa fallback)
export const mockSocialUsers = [
  { id: 'm1', username: 'ornek_kullanici_1', avatarUrl: null, lessonCount: 42, neighborhood: { name: 'Kadıköy' } },
  { id: 'm2', username: 'ornek_kullanici_2', avatarUrl: null, lessonCount: 38, neighborhood: { name: 'Beşiktaş' } },
  { id: 'm3', username: 'ornek_kullanici_3', avatarUrl: null, lessonCount: 31, neighborhood: { name: 'Şişli' } },
  { id: 'm4', username: 'ornek_kullanici_4', avatarUrl: null, lessonCount: 27, neighborhood: { name: 'Üsküdar' } },
  { id: 'm5', username: 'ornek_kullanici_5', avatarUrl: null, lessonCount: 24, neighborhood: { name: 'Bakırköy' } },
  { id: 'm6', username: 'ornek_kullanici_6', avatarUrl: null, lessonCount: 19, neighborhood: { name: 'Sarıyer' } },
  { id: 'm7', username: 'ornek_kullanici_7', avatarUrl: null, lessonCount: 15, neighborhood: { name: 'Maltepe' } },
]

export const mockSocialFeed = [
  { id: 'f1', type: 'class', user: { username: 'ornek_kullanici_3', fullName: 'Örnek Kullanıcı 3', avatarUrl: null }, category: 'Yoga', categoryColor: '#ed719e', title: 'Örnek Ders 1', venueName: 'Örnek Salon 1', date: new Date(Date.now() - 2 * 3600 * 1000).toISOString(), likeCount: 4, commentCount: 1, likedByMe: false },
  { id: 'f3', type: 'class', user: { username: 'ornek_kullanici_2', fullName: 'Örnek Kullanıcı 2', avatarUrl: null }, category: 'Boks', categoryColor: '#DC2626', title: 'Örnek Ders 3', venueName: 'Örnek Salon 3', date: new Date(Date.now() - 26 * 3600 * 1000).toISOString(), likeCount: 2, commentCount: 0, likedByMe: false },
]

export const mockSocialVenues = [
  { id: 'v1', name: 'Örnek Salon 1', avgRating: 4.9, totalReviews: 128, coverImageUrl: null, mainIcon: 'yoga', iconBg: '#F0FDF4', iconColor: '#16A34A', neighborhood: { name: 'Kadıköy' }, sportCategories: [{ sportCategory: { name: 'Yoga' } }, { sportCategory: { name: 'Pilates' } }, { sportCategory: { name: 'HIIT' } }] },
  { id: 'v2', name: 'Örnek Salon 2', avgRating: 4.8, totalReviews: 94, coverImageUrl: null, mainIcon: 'boxing', iconBg: '#FFF1F2', iconColor: '#E11D48', neighborhood: { name: 'Beşiktaş' }, sportCategories: [{ sportCategory: { name: 'Boks' } }, { sportCategory: { name: 'Crossfit' } }] },
  { id: 'v3', name: 'Örnek Salon 3', avgRating: 4.7, totalReviews: 73, coverImageUrl: null, mainIcon: 'yoga', iconBg: '#F0FDF4', iconColor: '#16A34A', neighborhood: { name: 'Şişli' }, sportCategories: [{ sportCategory: { name: 'Yoga' } }, { sportCategory: { name: 'Dans' } }] },
  { id: 'v5', name: 'Örnek Salon 4', avgRating: 4.5, totalReviews: 55, coverImageUrl: null, mainIcon: 'hiit', iconBg: '#FFF7ED', iconColor: '#EA580C', neighborhood: { name: 'Üsküdar' }, sportCategories: [{ sportCategory: { name: 'HIIT' } }, { sportCategory: { name: 'Pilates' } }] },
]
