export const mockUsers = [
  { id: 1, username: 'mehmet_k', fullName: 'Mehmet Kaya', bio: 'Yoga ve halı saha tutkunu. 🏃', neighborhood: 'Beşiktaş', tier: { name: 'Atlet', icon: 'zap', color: '#3B82F6', discountPercent: 10 }, topSports: [{ name: 'Yoga', icon: 'yoga', count: 34, color: '#C4A882' }, { name: 'Halı Saha', icon: 'football', count: 28, color: '#16A34A' }, { name: 'HIIT', icon: 'hiit', count: 22, color: '#F97316' }], stats: { totalLessons: 84, thisMonth: 12, streak: 6, noCancel: 18, sameVenue: 14 }, badges: [{ name: 'İstikrarlı', icon: 'target', color: '#8B5CF6' }, { name: 'Disiplinli', icon: 'strength', color: '#10B981' }], leaderboard: { istanbul: 142, neighborhood: 8 } },
  { id: 2, username: 'ali_demir', fullName: 'Ali Demir', bio: 'Boks ve fitness hayranı. 🥊', neighborhood: 'Kadıköy', tier: { name: 'Sporcu', icon: 'circle', color: '#10B981', discountPercent: 5 }, topSports: [{ name: 'Boks', icon: 'boxing', count: 40, color: '#DC2626' }, { name: 'Crossfit', icon: 'strength', count: 20, color: '#4B5563' }], stats: { totalLessons: 52, thisMonth: 8, streak: 4, noCancel: 12, sameVenue: 8 }, badges: [{ name: 'Disiplinli', icon: 'strength', color: '#10B981' }], leaderboard: { istanbul: 280, neighborhood: 15 } },
  { id: 3, username: 'selin_y', fullName: 'Selin Yıldız', bio: 'Yoga şampiyonu, meditasyon aşığı. 🧘', neighborhood: 'Şişli', tier: { name: 'Şampiyon', icon: 'trophy', color: '#F59E0B', discountPercent: 15 }, topSports: [{ name: 'Yoga', icon: 'yoga', count: 80, color: '#C4A882' }, { name: 'Pilates', icon: 'pilates', count: 45, color: '#C9849A' }], stats: { totalLessons: 134, thisMonth: 18, streak: 22, noCancel: 40, sameVenue: 35 }, badges: [{ name: 'İstikrarlı', icon: 'target', color: '#8B5CF6' }, { name: 'Disiplinli', icon: 'strength', color: '#10B981' }, { name: 'Sadık', icon: 'heart', color: '#EF4444' }], leaderboard: { istanbul: 24, neighborhood: 2 } },
  { id: 4, username: 'burak_k', fullName: 'Burak Kılıç', bio: 'Padel ve tenis tutkunu. 🎾', neighborhood: 'Ataşehir', tier: { name: 'Atlet', icon: 'zap', color: '#3B82F6', discountPercent: 10 }, topSports: [{ name: 'Padel', icon: 'padel', count: 50, color: '#EAB308' }, { name: 'Tenis', icon: 'padel', count: 22, color: '#F59E0B' }], stats: { totalLessons: 78, thisMonth: 10, streak: 8, noCancel: 20, sameVenue: 18 }, badges: [{ name: 'Sadık', icon: 'heart', color: '#EF4444' }], leaderboard: { istanbul: 168, neighborhood: 12 } },
  { id: 5, username: 'ece_a', fullName: 'Ece Arslan', bio: 'Pilates ve dans severim. 💃', neighborhood: 'Beşiktaş', tier: { name: 'Aday', icon: 'circle', color: '#8B5CF6', discountPercent: 0 }, topSports: [{ name: 'Pilates', icon: 'pilates', count: 12, color: '#C9849A' }, { name: 'Dans', icon: 'dance', count: 8, color: '#9333EA' }], stats: { totalLessons: 20, thisMonth: 5, streak: 2, noCancel: 5, sameVenue: 4 }, badges: [], leaderboard: { istanbul: 890, neighborhood: 42 } },
  { id: 6, username: 'emre_t', fullName: 'Emre Taş', bio: 'Halı saha ve basketbol. ⚽🏀', neighborhood: 'Levent', tier: { name: 'Sporcu', icon: 'circle', color: '#10B981', discountPercent: 5 }, topSports: [{ name: 'Halı Saha', icon: 'football', count: 30, color: '#16A34A' }, { name: 'Basketbol', icon: 'basketball', count: 18, color: '#C2501F' }], stats: { totalLessons: 48, thisMonth: 7, streak: 3, noCancel: 10, sameVenue: 6 }, badges: [{ name: 'İstikrarlı', icon: 'target', color: '#8B5CF6' }], leaderboard: { istanbul: 310, neighborhood: 18 } },
]

export const mockInstructors = [
  { id: 1001, userId: null, venueId: 1001, fullName: 'Ayşe Kaya', bio: '10 yıllık deneyimli yoga eğitmeni. Hindistan\'da 500 saatlik eğitim almıştır. Vinyasa ve Yin Yoga uzmanı.', bioEn: 'Yoga instructor with 10 years of experience. Completed 500 hours of training in India. Specialist in Vinyasa and Yin Yoga.', specialty: 'Vinyasa Flow · Yin Yoga', specialtyEn: 'Vinyasa Flow · Yin Yoga', avgRating: 4.9, totalReviews: 128, icon: 'yoga', color: '#C4A882', isActive: true },
  { id: 1002, userId: null, venueId: 1001, fullName: 'Murat Öz', bio: 'Ashtanga ve güç yogası konusunda sertifikalı eğitmen. 7 yıldır profesyonel eğitim veriyor.', bioEn: 'Certified instructor in Ashtanga and power yoga. Teaching professionally for 7 years.', specialty: 'Ashtanga · Güç Yogası', specialtyEn: 'Ashtanga · Power Yoga', avgRating: 4.8, totalReviews: 96, icon: 'weightlifting', color: '#3B82F6', isActive: true },
  { id: 1003, userId: null, venueId: 1002, fullName: 'Deniz Şahin', bio: 'Reformer pilates uzmanı. Fizyoterapi geçmişiyle rehabilitasyon odaklı pilates dersleri veriyor.', bioEn: 'Reformer pilates specialist. Offers rehabilitation-focused pilates classes with a physiotherapy background.', specialty: 'Reformer · Rehabilitasyon Pilates', specialtyEn: 'Reformer · Rehabilitation Pilates', avgRating: 4.8, totalReviews: 112, icon: 'pilates', color: '#C9849A', isActive: true },
  { id: 1004, userId: null, venueId: 1003, fullName: 'Mert Demir', bio: 'Eski milli boksör. 8 yıldır boks ve kickboks eğitmenliği yapıyor. Başlangıç ve ileri seviye dersler.', bioEn: 'Former national boxer. Coaching boxing and kickboxing for 8 years. Beginner and advanced classes.', specialty: 'Boks · Kickboks · MMA', specialtyEn: 'Boxing · Kickboxing · MMA', avgRating: 4.7, totalReviews: 89, icon: 'boxing', color: '#DC2626', isActive: true },
  { id: 1005, userId: null, venueId: 1005, fullName: 'Selin Arslan', bio: 'CrossFit L2 sertifikalı eğitmen. HIIT ve fonksiyonel fitness konusunda 6 yıllık deneyim.', bioEn: 'CrossFit L2 certified instructor. 6 years of experience in HIIT and functional fitness.', specialty: 'HIIT · CrossFit · Fonksiyonel', specialtyEn: 'HIIT · CrossFit · Functional', avgRating: 4.9, totalReviews: 156, icon: 'hiit', color: '#F97316', isActive: true },
  { id: 1006, userId: null, venueId: 1001, fullName: 'Selin Yıldız', bio: 'Pilates ve yoga eğitmeni. Hem studio hem reformer pilates konusunda uzman.', bioEn: 'Pilates and yoga instructor. Expert in both studio and reformer pilates.', specialty: 'Pilates · Yoga', specialtyEn: 'Pilates · Yoga', avgRating: 4.7, totalReviews: 74, icon: 'wellness', color: '#10B981', isActive: true },
]

export const mockVenues = [
  { id: 1001, name: 'Zen Studio Beşiktaş', description: 'İstanbul\'un kalbinde, Beşiktaş\'ta konumlanan Zen Studio; yoga, pilates ve meditasyon alanında İstanbul\'un en prestijli stüdyolarından biridir.', descriptionEn: 'Located in the heart of Istanbul in Beşiktaş, Zen Studio is one of the city\'s most prestigious studios for yoga, pilates and meditation.', category: 'Yoga · Pilates · Meditasyon', categoryEn: 'Yoga · Pilates · Meditation', address: 'Sinanpaşa Mah. Çırağan Cad. No:42, Beşiktaş/İstanbul', neighborhood: 'Beşiktaş', avgRating: 4.9, totalReviews: 214, isVerified: true, coverEmoji: 'yoga', color: '#C4A882', amenities: ['Duş', 'Soyunma odası', 'Klima', 'Mat dahil', 'Ücretsiz su', 'Wifi', 'Otopark'], instructorIds: [1001, 1002, 1006] },
  { id: 1002, name: 'Core Pilates Kadıköy', description: 'Kadıköy\'ün merkezinde, modern ekipmanlarla donatılmış pilates stüdyosu. Reformer ve studio pilates dersleri.', descriptionEn: 'A modern, fully-equipped pilates studio in the center of Kadıköy. Reformer and studio pilates classes.', category: 'Pilates · Yoga', categoryEn: 'Pilates · Yoga', address: 'Moda Cad. No:88, Kadıköy/İstanbul', neighborhood: 'Kadıköy', avgRating: 4.8, totalReviews: 178, isVerified: true, coverEmoji: 'pilates', color: '#C9849A', amenities: ['Reformer', 'Duş', 'Klima', 'Havlu dahil', 'Ücretsiz su'], instructorIds: [1003] },
  { id: 1003, name: 'Fight Club Şişli', description: 'Profesyonel boks salonu. Ring, kum torbaları ve tam donanımlı spor alanı. Başlangıçtan ileri seviyeye her şey.', descriptionEn: 'A professional boxing gym. Ring, punching bags and a fully-equipped training area. Everything from beginner to advanced.', category: 'Boks · Kickboks · MMA', categoryEn: 'Boxing · Kickboxing · MMA', address: 'Halaskargazi Cad. No:156, Şişli/İstanbul', neighborhood: 'Şişli', avgRating: 4.7, totalReviews: 142, isVerified: true, coverEmoji: 'boxing', color: '#DC2626', amenities: ['Ring', 'Kum torbası', 'Eldiven kiralama', 'Duş', 'Soyunma odası'], instructorIds: [1004] },
  { id: 1004, name: 'Padel Istanbul Maslak', description: 'İstanbul\'un en büyük padel kompleksi. 8 kapalı saha, kafeterya ve profesyonel eğitmenler.', descriptionEn: 'Istanbul\'s largest padel complex. 8 indoor courts, a cafeteria and professional coaches.', category: 'Padel · Tenis', categoryEn: 'Padel · Tennis', address: 'Büyükdere Cad. No:201, Maslak/İstanbul', neighborhood: 'Maslak', avgRating: 4.8, totalReviews: 198, isVerified: true, coverEmoji: 'padel', color: '#EAB308', amenities: ['8 kapalı saha', 'Raket kiralama', 'Top dahil', 'Kafeterya', 'Otopark'], instructorIds: [] },
  { id: 1005, name: 'FitZone Levent', description: 'Levent\'in en modern spor merkezi. HIIT, CrossFit ve fonksiyonel fitness alanında uzman kadro.', descriptionEn: 'Levent\'s most modern fitness center. An expert team in HIIT, CrossFit and functional fitness.', category: 'HIIT · CrossFit · Fonksiyonel', categoryEn: 'HIIT · CrossFit · Functional', address: 'Nisbetiye Cad. No:24, Levent/İstanbul', neighborhood: 'Levent', avgRating: 4.9, totalReviews: 267, isVerified: true, coverEmoji: 'hiit', color: '#F97316', amenities: ['Modern ekipman', 'Duş', 'Klima', 'Havlu dahil', 'Protein bar', 'Otopark'], instructorIds: [1005] },
  { id: 1006, name: 'Spor Arena Ataşehir', description: 'Ataşehir\'in en büyük spor kompleksi. Halı saha, basketbol kortu ve padel sahaları.', descriptionEn: 'Ataşehir\'s largest sports complex. Football pitches, basketball courts and padel courts.', category: 'Halı Saha · Basketbol · Padel', categoryEn: 'Football · Basketball · Padel', address: 'Küçükbakkalköy Mah. Alemdağ Cad. No:12, Ataşehir/İstanbul', neighborhood: 'Ataşehir', avgRating: 4.6, totalReviews: 134, isVerified: false, coverEmoji: 'football', color: '#16A34A', amenities: ['3 halı saha', '2 basketbol kortu', 'Duş', 'Soyunma odası', 'Top dahil', 'Işıklı saha', 'Otopark'], instructorIds: [] },
]

export const mockClasses = [
  { id: 1001, title: 'Vinyasa Flow Yoga', venueId: 1001, instructorId: 1001, category: 'Yoga', icon: 'yoga', time: 'Bugün 09:00', date: '10 Haziran 2026, Salı', duration: '60 dk', basePrice: 350, spots: 4, capacity: 12, rating: 4.9, totalReviews: 214, neighborhood: 'Beşiktaş', color: '#C4A882', description: 'Nefes ile hareketin senkronize edildiği dinamik yoga stili. Tüm seviyeler için uygundur.', descriptionEn: 'A dynamic yoga style synchronizing breath with movement. Suitable for all levels.', amenities: ['Yoga matı dahil', 'Duş imkânı', 'Ücretsiz su', 'Klima'] },
  { id: 1002, title: 'Reformer Pilates', venueId: 1002, instructorId: 1003, category: 'Pilates', icon: 'pilates', time: 'Bugün 10:30', date: '10 Haziran 2026, Salı', duration: '50 dk', basePrice: 420, spots: 2, capacity: 8, rating: 4.8, totalReviews: 178, neighborhood: 'Kadıköy', color: '#C9849A', description: 'Reformer makinesiyle yapılan pilates dersi. Vücut hizalanması ve güç geliştirme odaklı.', descriptionEn: 'A pilates class on the reformer machine, focused on body alignment and strength building.', amenities: ['Reformer dahil', 'Havlu dahil', 'Ücretsiz su'] },
  { id: 1003, title: 'Kickboks Başlangıç', titleEn: 'Kickboxing Basics', venueId: 1003, instructorId: 1004, category: 'Boks', icon: 'boxing', time: 'Bugün 12:00', date: '10 Haziran 2026, Salı', duration: '60 dk', basePrice: 300, spots: 6, capacity: 15, rating: 4.7, totalReviews: 142, neighborhood: 'Şişli', color: '#DC2626', description: 'Başlangıç seviye kickboks dersi. Temel teknikler, kondisyon ve koordinasyon geliştirme.', descriptionEn: 'A beginner-level kickboxing class. Basic techniques, conditioning and coordination.', amenities: ['Eldiven kiralama', 'Kask dahil', 'Duş'] },
  { id: 1004, title: 'HIIT Blast', venueId: 1005, instructorId: 1005, category: 'HIIT', icon: 'hiit', time: 'Bugün 18:00', date: '10 Haziran 2026, Salı', duration: '45 dk', basePrice: 280, spots: 8, capacity: 20, rating: 4.9, totalReviews: 267, neighborhood: 'Levent', color: '#F97316', description: 'Yüksek yoğunluklu interval antrenman. 45 dakikada maksimum kalori yakımı.', descriptionEn: 'High-intensity interval training. Maximum calorie burn in 45 minutes.', amenities: ['Ekipman dahil', 'Havlu dahil', 'Protein içeceği'] },
  { id: 1005, title: 'Yin Yoga', venueId: 1001, instructorId: 1001, category: 'Yoga', icon: 'yoga', time: 'Yarın 09:00', date: '11 Haziran 2026, Çarşamba', duration: '75 dk', basePrice: 320, spots: 8, capacity: 12, rating: 4.9, totalReviews: 186, neighborhood: 'Beşiktaş', color: '#C4A882', description: 'Derin doku çalışması ve esneklik geliştirme. Sakin ve içe dönük bir yoga pratiği.', descriptionEn: 'Deep tissue work and flexibility development. A calm, introspective yoga practice.', amenities: ['Yoga matı dahil', 'Yoga bloğu dahil', 'Ücretsiz su'] },
  { id: 1006, title: 'Güç Yogası', titleEn: 'Power Yoga', venueId: 1001, instructorId: 1002, category: 'Yoga', icon: 'strength', time: 'Yarın 12:00', date: '11 Haziran 2026, Çarşamba', duration: '60 dk', basePrice: 380, spots: 5, capacity: 12, rating: 4.8, totalReviews: 156, neighborhood: 'Beşiktaş', color: '#3B82F6', description: 'Güç ve dayanıklılık geliştiren dinamik yoga stili. Orta ve ileri seviye için önerilir.', descriptionEn: 'A dynamic yoga style building strength and endurance. Recommended for intermediate and advanced levels.', amenities: ['Yoga matı dahil', 'Duş', 'Ücretsiz su'] },
]

export const mockDropInSlots = [
  { id: 1001, title: '7v7 Halı Saha Maçı', titleEn: '7v7 Football Match', venueId: 1006, category: 'Halı Saha', icon: 'football', color: '#16A34A', format: '7v7', totalPlayers: 14, currentPlayers: 9, date: '10 Haziran 2026, Salı', time: 'Bugün 19:00', endsAt: '20:30', duration: '90 dk', totalPrice: 2800, pricePerPerson: 200, visibility: 'open', neighborhood: 'Ataşehir', teams: { A: [{ id: 1, username: 'mehmet_k', tier: 'Atlet', tierColor: '#3B82F6' }, { id: 2, username: 'ali_demir', tier: 'Sporcu', tierColor: '#10B981' }, { id: 3, username: 'emre_t', tier: 'Sporcu', tierColor: '#10B981' }, { id: 4, username: 'burak_k', tier: 'Atlet', tierColor: '#3B82F6' }], B: [{ id: 5, username: 'selin_y', tier: 'Şampiyon', tierColor: '#F59E0B' }, { id: 6, username: 'ece_a', tier: 'Aday', tierColor: '#8B5CF6' }, { id: 7, username: 'kerem_a', tier: 'Sporcu', tierColor: '#10B981' }, { id: 8, username: 'berk_o', tier: 'Aday', tierColor: '#8B5CF6' }, { id: 9, username: 'arda_m', tier: 'Sporcu', tierColor: '#10B981' }] }, openSpots: { A: 3, B: 2 } },
  { id: 1002, title: '2v2 Padel', titleEn: '2v2 Padel', venueId: 1004, category: 'Padel', icon: 'padel', color: '#EAB308', format: '2v2', totalPlayers: 4, currentPlayers: 2, date: '10 Haziran 2026, Salı', time: 'Bugün 20:00', endsAt: '21:00', duration: '60 dk', totalPrice: 800, pricePerPerson: 200, visibility: 'open', neighborhood: 'Maslak', teams: { A: [{ id: 1, username: 'burak_k', tier: 'Atlet', tierColor: '#3B82F6' }], B: [{ id: 2, username: 'emre_t', tier: 'Sporcu', tierColor: '#10B981' }] }, openSpots: { A: 1, B: 1 } },
  { id: 1003, title: '5v5 Basketbol', titleEn: '5v5 Basketball', venueId: 1006, category: 'Basketbol', icon: 'basketball', color: '#C2501F', format: '5v5', totalPlayers: 10, currentPlayers: 6, date: '11 Haziran 2026, Çarşamba', time: 'Yarın 18:00', endsAt: '19:30', duration: '90 dk', totalPrice: 1500, pricePerPerson: 150, visibility: 'open', neighborhood: 'Ataşehir', teams: { A: [{ id: 1, username: 'mehmet_k', tier: 'Atlet', tierColor: '#3B82F6' }, { id: 2, username: 'ali_demir', tier: 'Sporcu', tierColor: '#10B981' }, { id: 3, username: 'emre_t', tier: 'Sporcu', tierColor: '#10B981' }], B: [{ id: 4, username: 'burak_k', tier: 'Atlet', tierColor: '#3B82F6' }, { id: 5, username: 'kerem_a', tier: 'Sporcu', tierColor: '#10B981' }, { id: 6, username: 'berk_o', tier: 'Aday', tierColor: '#8B5CF6' }] }, openSpots: { A: 2, B: 2 } },
]

// Sosyal sayfası demo verisi (API boşsa fallback) — özel isimler/mahalleler çevrilmez
export const mockSocialUsers = [
  { id: 'm1', username: 'zeynep_aktif', avatarUrl: null, lessonCount: 42, neighborhood: { name: 'Kadıköy' } },
  { id: 'm2', username: 'baris_sporcu', avatarUrl: null, lessonCount: 38, neighborhood: { name: 'Beşiktaş' } },
  { id: 'm3', username: 'elif_yoga', avatarUrl: null, lessonCount: 31, neighborhood: { name: 'Şişli' } },
  { id: 'm4', username: 'mert_boks', avatarUrl: null, lessonCount: 27, neighborhood: { name: 'Üsküdar' } },
  { id: 'm5', username: 'selin_pilates', avatarUrl: null, lessonCount: 24, neighborhood: { name: 'Bakırköy' } },
  { id: 'm6', username: 'ahmet_crossfit', avatarUrl: null, lessonCount: 19, neighborhood: { name: 'Sarıyer' } },
  { id: 'm7', username: 'dila_dans', avatarUrl: null, lessonCount: 15, neighborhood: { name: 'Maltepe' } },
]

export const mockSocialFeed = [
  { id: 'f1', type: 'class', user: { username: 'selin_y', fullName: 'Selin Yıldız', avatarUrl: null }, category: 'Yoga', categoryColor: '#C4A882', title: 'Vinyasa Flow Yoga', venueName: 'Zen Studio Beşiktaş', date: new Date(Date.now() - 2 * 3600 * 1000).toISOString(), likeCount: 4, commentCount: 1, likedByMe: false },
  { id: 'f2', type: 'dropin', user: { username: 'ali_demir', fullName: 'Ali Demir', avatarUrl: null }, category: 'Halı Saha', categoryColor: '#16A34A', title: '7v7 Halı Saha Maçı', venueName: 'Spor Arena Ataşehir', date: new Date(Date.now() - 5 * 3600 * 1000).toISOString(), likeCount: 9, commentCount: 3, likedByMe: false },
  { id: 'f3', type: 'class', user: { username: 'mert_boks', fullName: 'Mert Boks', avatarUrl: null }, category: 'Boks', categoryColor: '#DC2626', title: 'Kickboks Başlangıç', venueName: 'Fight Club Şişli', date: new Date(Date.now() - 26 * 3600 * 1000).toISOString(), likeCount: 2, commentCount: 0, likedByMe: false },
]

export const mockSocialVenues = [
  { id: 'v1', name: 'Kadıköy Spor Merkezi', avgRating: 4.9, totalReviews: 128, coverImageUrl: null, mainIcon: 'yoga', iconBg: '#F0FDF4', iconColor: '#16A34A', neighborhood: { name: 'Kadıköy' }, sportCategories: [{ sportCategory: { name: 'Yoga' } }, { sportCategory: { name: 'Pilates' } }, { sportCategory: { name: 'HIIT' } }] },
  { id: 'v2', name: 'Beşiktaş Boks Kulübü', avgRating: 4.8, totalReviews: 94, coverImageUrl: null, mainIcon: 'boxing', iconBg: '#FFF1F2', iconColor: '#E11D48', neighborhood: { name: 'Beşiktaş' }, sportCategories: [{ sportCategory: { name: 'Boks' } }, { sportCategory: { name: 'Crossfit' } }] },
  { id: 'v3', name: 'Flow Yoga Studio', avgRating: 4.7, totalReviews: 73, coverImageUrl: null, mainIcon: 'yoga', iconBg: '#F0FDF4', iconColor: '#16A34A', neighborhood: { name: 'Şişli' }, sportCategories: [{ sportCategory: { name: 'Yoga' } }, { sportCategory: { name: 'Dans' } }] },
  { id: 'v4', name: 'Padel İstanbul', avgRating: 4.6, totalReviews: 61, coverImageUrl: null, mainIcon: 'padel', iconBg: '#EFF6FF', iconColor: '#2563EB', neighborhood: { name: 'Sarıyer' }, sportCategories: [{ sportCategory: { name: 'Padel' } }] },
  { id: 'v5', name: 'Üsküdar Fitness Club', avgRating: 4.5, totalReviews: 55, coverImageUrl: null, mainIcon: 'hiit', iconBg: '#FFF7ED', iconColor: '#EA580C', neighborhood: { name: 'Üsküdar' }, sportCategories: [{ sportCategory: { name: 'HIIT' } }, { sportCategory: { name: 'Pilates' } }] },
]
