export const mockUsers = [
  { id: 1, username: 'mehmet_k', fullName: 'Mehmet Kaya', bio: 'Yoga ve halı saha tutkunu. 🏃', neighborhood: 'Beşiktaş', tier: { name: 'Atlet', icon: 'zap', color: '#3B82F6', discountPercent: 10 }, topSports: [{ name: 'Yoga', icon: 'yoga', count: 34, color: '#C4A882' }, { name: 'Halı Saha', icon: 'football', count: 28, color: '#16A34A' }, { name: 'HIIT', icon: 'hiit', count: 22, color: '#F97316' }], stats: { totalLessons: 84, thisMonth: 12, streak: 6, noCancel: 18, sameVenue: 14 }, badges: [{ name: 'İstikrarlı', icon: 'target', color: '#8B5CF6' }, { name: 'Disiplinli', icon: 'strength', color: '#10B981' }], leaderboard: { istanbul: 142, neighborhood: 8 } },
  { id: 2, username: 'ali_demir', fullName: 'Ali Demir', bio: 'Boks ve fitness hayranı. 🥊', neighborhood: 'Kadıköy', tier: { name: 'Sporcu', icon: 'circle', color: '#10B981', discountPercent: 5 }, topSports: [{ name: 'Boks', icon: 'boxing', count: 40, color: '#DC2626' }, { name: 'Crossfit', icon: 'strength', count: 20, color: '#4B5563' }], stats: { totalLessons: 52, thisMonth: 8, streak: 4, noCancel: 12, sameVenue: 8 }, badges: [{ name: 'Disiplinli', icon: 'strength', color: '#10B981' }], leaderboard: { istanbul: 280, neighborhood: 15 } },
  { id: 3, username: 'selin_y', fullName: 'Selin Yıldız', bio: 'Yoga şampiyonu, meditasyon aşığı. 🧘', neighborhood: 'Şişli', tier: { name: 'Şampiyon', icon: 'trophy', color: '#F59E0B', discountPercent: 15 }, topSports: [{ name: 'Yoga', icon: 'yoga', count: 80, color: '#C4A882' }, { name: 'Pilates', icon: 'pilates', count: 45, color: '#C9849A' }], stats: { totalLessons: 134, thisMonth: 18, streak: 22, noCancel: 40, sameVenue: 35 }, badges: [{ name: 'İstikrarlı', icon: 'target', color: '#8B5CF6' }, { name: 'Disiplinli', icon: 'strength', color: '#10B981' }, { name: 'Sadık', icon: 'heart', color: '#EF4444' }], leaderboard: { istanbul: 24, neighborhood: 2 } },
  { id: 4, username: 'burak_k', fullName: 'Burak Kılıç', bio: 'Padel ve tenis tutkunu. 🎾', neighborhood: 'Ataşehir', tier: { name: 'Atlet', icon: 'zap', color: '#3B82F6', discountPercent: 10 }, topSports: [{ name: 'Padel', icon: 'padel', count: 50, color: '#EAB308' }, { name: 'Tenis', icon: 'padel', count: 22, color: '#F59E0B' }], stats: { totalLessons: 78, thisMonth: 10, streak: 8, noCancel: 20, sameVenue: 18 }, badges: [{ name: 'Sadık', icon: 'heart', color: '#EF4444' }], leaderboard: { istanbul: 168, neighborhood: 12 } },
  { id: 5, username: 'ece_a', fullName: 'Ece Arslan', bio: 'Pilates ve dans severim. 💃', neighborhood: 'Beşiktaş', tier: { name: 'Aday', icon: 'circle', color: '#8B5CF6', discountPercent: 0 }, topSports: [{ name: 'Pilates', icon: 'pilates', count: 12, color: '#C9849A' }, { name: 'Dans', icon: 'dance', count: 8, color: '#9333EA' }], stats: { totalLessons: 20, thisMonth: 5, streak: 2, noCancel: 5, sameVenue: 4 }, badges: [], leaderboard: { istanbul: 890, neighborhood: 42 } },
  { id: 6, username: 'emre_t', fullName: 'Emre Taş', bio: 'Halı saha ve basketbol. ⚽🏀', neighborhood: 'Levent', tier: { name: 'Sporcu', icon: 'circle', color: '#10B981', discountPercent: 5 }, topSports: [{ name: 'Halı Saha', icon: 'football', count: 30, color: '#16A34A' }, { name: 'Basketbol', icon: 'basketball', count: 18, color: '#C2501F' }], stats: { totalLessons: 48, thisMonth: 7, streak: 3, noCancel: 10, sameVenue: 6 }, badges: [{ name: 'İstikrarlı', icon: 'target', color: '#8B5CF6' }], leaderboard: { istanbul: 310, neighborhood: 18 } },
]

export const mockInstructors = [
  { id: 1, userId: null, venueId: 1, fullName: 'Ayşe Kaya', bio: '10 yıllık deneyimli yoga eğitmeni. Hindistan\'da 500 saatlik eğitim almıştır. Vinyasa ve Yin Yoga uzmanı.', specialty: 'Vinyasa Flow · Yin Yoga', avgRating: 4.9, totalReviews: 128, icon: 'yoga', color: '#C4A882', isActive: true },
  { id: 2, userId: null, venueId: 1, fullName: 'Murat Öz', bio: 'Ashtanga ve güç yogası konusunda sertifikalı eğitmen. 7 yıldır profesyonel eğitim veriyor.', specialty: 'Ashtanga · Güç Yogası', avgRating: 4.8, totalReviews: 96, icon: 'weightlifting', color: '#3B82F6', isActive: true },
  { id: 3, userId: null, venueId: 2, fullName: 'Deniz Şahin', bio: 'Reformer pilates uzmanı. Fizyoterapi geçmişiyle rehabilitasyon odaklı pilates dersleri veriyor.', specialty: 'Reformer · Rehabilitasyon Pilates', avgRating: 4.8, totalReviews: 112, icon: 'pilates', color: '#C9849A', isActive: true },
  { id: 4, userId: null, venueId: 3, fullName: 'Mert Demir', bio: 'Eski milli boksör. 8 yıldır boks ve kickboks eğitmenliği yapıyor. Başlangıç ve ileri seviye dersler.', specialty: 'Boks · Kickboks · MMA', avgRating: 4.7, totalReviews: 89, icon: 'boxing', color: '#DC2626', isActive: true },
  { id: 5, userId: null, venueId: 5, fullName: 'Selin Arslan', bio: 'CrossFit L2 sertifikalı eğitmen. HIIT ve fonksiyonel fitness konusunda 6 yıllık deneyim.', specialty: 'HIIT · CrossFit · Fonksiyonel', avgRating: 4.9, totalReviews: 156, icon: 'hiit', color: '#F97316', isActive: true },
  { id: 6, userId: null, venueId: 1, fullName: 'Selin Yıldız', bio: 'Pilates ve yoga eğitmeni. Hem studio hem reformer pilates konusunda uzman.', specialty: 'Pilates · Yoga', avgRating: 4.7, totalReviews: 74, icon: 'wellness', color: '#10B981', isActive: true },
]

export const mockVenues = [
  { id: 1, name: 'Zen Studio Beşiktaş', description: 'İstanbul\'un kalbinde, Beşiktaş\'ta konumlanan Zen Studio; yoga, pilates ve meditasyon alanında İstanbul\'un en prestijli stüdyolarından biridir.', category: 'Yoga · Pilates · Meditasyon', address: 'Sinanpaşa Mah. Çırağan Cad. No:42, Beşiktaş/İstanbul', neighborhood: 'Beşiktaş', avgRating: 4.9, totalReviews: 214, isVerified: true, coverEmoji: 'yoga', color: '#C4A882', amenities: ['Duş', 'Soyunma odası', 'Klima', 'Mat dahil', 'Ücretsiz su', 'Wifi', 'Otopark'], instructorIds: [1, 2, 6] },
  { id: 2, name: 'Core Pilates Kadıköy', description: 'Kadıköy\'ün merkezinde, modern ekipmanlarla donatılmış pilates stüdyosu. Reformer ve studio pilates dersleri.', category: 'Pilates · Yoga', address: 'Moda Cad. No:88, Kadıköy/İstanbul', neighborhood: 'Kadıköy', avgRating: 4.8, totalReviews: 178, isVerified: true, coverEmoji: 'pilates', color: '#C9849A', amenities: ['Reformer', 'Duş', 'Klima', 'Havlu dahil', 'Ücretsiz su'], instructorIds: [3] },
  { id: 3, name: 'Fight Club Şişli', description: 'Profesyonel boks salonu. Ring, kum torbaları ve tam donanımlı spor alanı. Başlangıçtan ileri seviyeye her şey.', category: 'Boks · Kickboks · MMA', address: 'Halaskargazi Cad. No:156, Şişli/İstanbul', neighborhood: 'Şişli', avgRating: 4.7, totalReviews: 142, isVerified: true, coverEmoji: 'boxing', color: '#DC2626', amenities: ['Ring', 'Kum torbası', 'Eldiven kiralama', 'Duş', 'Soyunma odası'], instructorIds: [4] },
  { id: 4, name: 'Padel Istanbul Maslak', description: 'İstanbul\'un en büyük padel kompleksi. 8 kapalı saha, kafeterya ve profesyonel eğitmenler.', category: 'Padel · Tenis', address: 'Büyükdere Cad. No:201, Maslak/İstanbul', neighborhood: 'Maslak', avgRating: 4.8, totalReviews: 198, isVerified: true, coverEmoji: 'padel', color: '#EAB308', amenities: ['8 kapalı saha', 'Raket kiralama', 'Top dahil', 'Kafeterya', 'Otopark'], instructorIds: [] },
  { id: 5, name: 'FitZone Levent', description: 'Levent\'in en modern spor merkezi. HIIT, CrossFit ve fonksiyonel fitness alanında uzman kadro.', category: 'HIIT · CrossFit · Fonksiyonel', address: 'Nisbetiye Cad. No:24, Levent/İstanbul', neighborhood: 'Levent', avgRating: 4.9, totalReviews: 267, isVerified: true, coverEmoji: 'hiit', color: '#F97316', amenities: ['Modern ekipman', 'Duş', 'Klima', 'Havlu dahil', 'Protein bar', 'Otopark'], instructorIds: [5] },
  { id: 6, name: 'Spor Arena Ataşehir', description: 'Ataşehir\'in en büyük spor kompleksi. Halı saha, basketbol kortu ve padel sahaları.', category: 'Halı Saha · Basketbol · Padel', address: 'Küçükbakkalköy Mah. Alemdağ Cad. No:12, Ataşehir/İstanbul', neighborhood: 'Ataşehir', avgRating: 4.6, totalReviews: 134, isVerified: false, coverEmoji: 'football', color: '#16A34A', amenities: ['3 halı saha', '2 basketbol kortu', 'Duş', 'Soyunma odası', 'Top dahil', 'Işıklı saha', 'Otopark'], instructorIds: [] },
]

export const mockClasses = [
  { id: 1, title: 'Vinyasa Flow Yoga', venueId: 1, instructorId: 1, category: 'Yoga', icon: 'yoga', time: 'Bugün 09:00', date: '10 Haziran 2026, Salı', duration: '60 dk', basePrice: 350, spots: 4, capacity: 12, rating: 4.9, totalReviews: 214, neighborhood: 'Beşiktaş', color: '#C4A882', description: 'Nefes ile hareketin senkronize edildiği dinamik yoga stili. Tüm seviyeler için uygundur.', amenities: ['Yoga matı dahil', 'Duş imkânı', 'Ücretsiz su', 'Klima'] },
  { id: 2, title: 'Reformer Pilates', venueId: 2, instructorId: 3, category: 'Pilates', icon: 'pilates', time: 'Bugün 10:30', date: '10 Haziran 2026, Salı', duration: '50 dk', basePrice: 420, spots: 2, capacity: 8, rating: 4.8, totalReviews: 178, neighborhood: 'Kadıköy', color: '#C9849A', description: 'Reformer makinesiyle yapılan pilates dersi. Vücut hizalanması ve güç geliştirme odaklı.', amenities: ['Reformer dahil', 'Havlu dahil', 'Ücretsiz su'] },
  { id: 3, title: 'Kickboks Başlangıç', venueId: 3, instructorId: 4, category: 'Boks', icon: 'boxing', time: 'Bugün 12:00', date: '10 Haziran 2026, Salı', duration: '60 dk', basePrice: 300, spots: 6, capacity: 15, rating: 4.7, totalReviews: 142, neighborhood: 'Şişli', color: '#DC2626', description: 'Başlangıç seviye kickboks dersi. Temel teknikler, kondisyon ve koordinasyon geliştirme.', amenities: ['Eldiven kiralama', 'Kask dahil', 'Duş'] },
  { id: 4, title: 'HIIT Blast', venueId: 5, instructorId: 5, category: 'HIIT', icon: 'hiit', time: 'Bugün 18:00', date: '10 Haziran 2026, Salı', duration: '45 dk', basePrice: 280, spots: 8, capacity: 20, rating: 4.9, totalReviews: 267, neighborhood: 'Levent', color: '#F97316', description: 'Yüksek yoğunluklu interval antrenman. 45 dakikada maksimum kalori yakımı.', amenities: ['Ekipman dahil', 'Havlu dahil', 'Protein içeceği'] },
  { id: 5, title: 'Yin Yoga', venueId: 1, instructorId: 1, category: 'Yoga', icon: 'yoga', time: 'Yarın 09:00', date: '11 Haziran 2026, Çarşamba', duration: '75 dk', basePrice: 320, spots: 8, capacity: 12, rating: 4.9, totalReviews: 186, neighborhood: 'Beşiktaş', color: '#C4A882', description: 'Derin doku çalışması ve esneklik geliştirme. Sakin ve içe dönük bir yoga pratiği.', amenities: ['Yoga matı dahil', 'Yoga bloğu dahil', 'Ücretsiz su'] },
  { id: 6, title: 'Güç Yogası', venueId: 1, instructorId: 2, category: 'Yoga', icon: 'strength', time: 'Yarın 12:00', date: '11 Haziran 2026, Çarşamba', duration: '60 dk', basePrice: 380, spots: 5, capacity: 12, rating: 4.8, totalReviews: 156, neighborhood: 'Beşiktaş', color: '#3B82F6', description: 'Güç ve dayanıklılık geliştiren dinamik yoga stili. Orta ve ileri seviye için önerilir.', amenities: ['Yoga matı dahil', 'Duş', 'Ücretsiz su'] },
]

export const mockDropInSlots = [
  { id: 1, title: '7v7 Halı Saha Maçı', venueId: 6, category: 'Halı Saha', icon: 'football', color: '#16A34A', format: '7v7', totalPlayers: 14, currentPlayers: 9, date: '10 Haziran 2026, Salı', time: 'Bugün 19:00', endsAt: '20:30', duration: '90 dk', totalPrice: 2800, pricePerPerson: 200, visibility: 'open', neighborhood: 'Ataşehir', teams: { A: [{ id: 1, username: 'mehmet_k', tier: 'Atlet', tierColor: '#3B82F6' }, { id: 2, username: 'ali_demir', tier: 'Sporcu', tierColor: '#10B981' }, { id: 3, username: 'emre_t', tier: 'Sporcu', tierColor: '#10B981' }, { id: 4, username: 'burak_k', tier: 'Atlet', tierColor: '#3B82F6' }], B: [{ id: 5, username: 'selin_y', tier: 'Şampiyon', tierColor: '#F59E0B' }, { id: 6, username: 'ece_a', tier: 'Aday', tierColor: '#8B5CF6' }, { id: 7, username: 'kerem_a', tier: 'Sporcu', tierColor: '#10B981' }, { id: 8, username: 'berk_o', tier: 'Aday', tierColor: '#8B5CF6' }, { id: 9, username: 'arda_m', tier: 'Sporcu', tierColor: '#10B981' }] }, openSpots: { A: 3, B: 2 } },
  { id: 2, title: '2v2 Padel', venueId: 4, category: 'Padel', icon: 'padel', color: '#EAB308', format: '2v2', totalPlayers: 4, currentPlayers: 2, date: '10 Haziran 2026, Salı', time: 'Bugün 20:00', endsAt: '21:00', duration: '60 dk', totalPrice: 800, pricePerPerson: 200, visibility: 'open', neighborhood: 'Maslak', teams: { A: [{ id: 1, username: 'burak_k', tier: 'Atlet', tierColor: '#3B82F6' }], B: [{ id: 2, username: 'emre_t', tier: 'Sporcu', tierColor: '#10B981' }] }, openSpots: { A: 1, B: 1 } },
  { id: 3, title: '5v5 Basketbol', venueId: 6, category: 'Basketbol', icon: 'basketball', color: '#C2501F', format: '5v5', totalPlayers: 10, currentPlayers: 6, date: '11 Haziran 2026, Çarşamba', time: 'Yarın 18:00', endsAt: '19:30', duration: '90 dk', totalPrice: 1500, pricePerPerson: 150, visibility: 'open', neighborhood: 'Ataşehir', teams: { A: [{ id: 1, username: 'mehmet_k', tier: 'Atlet', tierColor: '#3B82F6' }, { id: 2, username: 'ali_demir', tier: 'Sporcu', tierColor: '#10B981' }, { id: 3, username: 'emre_t', tier: 'Sporcu', tierColor: '#10B981' }], B: [{ id: 4, username: 'burak_k', tier: 'Atlet', tierColor: '#3B82F6' }, { id: 5, username: 'kerem_a', tier: 'Sporcu', tierColor: '#10B981' }, { id: 6, username: 'berk_o', tier: 'Aday', tierColor: '#8B5CF6' }] }, openSpots: { A: 2, B: 2 } },
]
